### ISSUE TITLE
Bug in generating extended trapezoid gradient

### ISSUE THREAD

**Issue by felixdietz** [pulseq-frame/pulseq-zero#2]
t1 = torch.as_tensor(grad.times[:-1])
        t2 = torch.as_tensor(grad.times[1:])
        c1 = torch.as_tensor(grad.amplitudes[:-1])
        c2 = torch.as_tensor(grad.amplitudes[1:])

has to be changed to 

        t1 = torch.as_tensor(grad.tt[:-1])
        t2 = torch.as_tensor(grad.tt[1:])
        c1 = torch.as_tensor(grad.waveform[:-1])
        c2 = torch.as_tensor(grad.waveform[1:])

**Comment by J-Endres** [comment]
fixed by c3f86bd3c52afbb0cf708e679b1d849624a4a536
