### ISSUE TITLE
Missmatch of timing in gradients

### ISSUE THREAD

**Issue by SWeinmueller** [pulseq-frame/pulseq-zero#4]
Gradient rise time and fall time are wrong when using pulseq_zero:
rfex, gz90, gz90_bal = pp.make_sinc_pulse(**kwargs)

When using gr90.rise_time during seq generation, a wrong sequence could be the result.

Why is it like that?

[Example.txt](https://github.com/user-attachments/files/17872636/Example.txt)

**Comment by SWeinmueller** [comment]
https://github.com/pulseq-frame/pulseq-zero/blob/27599777c1cb4ccaf6eba8ca787aee33a160b1b5/src/pulseqzero/adapter/grads.py#L79C1-L80C48

In pypulseq they round the rise time to the grad_raster_time
https://github.com/imr-framework/pypulseq/blob/7b8c3ec18b593a5d093c7990eb6647457099f15e/pypulseq/make_trapezoid.py#L153-L161

**Comment by J-Endres** [comment]
Closed by 61a8129475deb2fc4a1a68c7b0aef9f552bb58b4 (see #8)
