### ISSUE TITLE
seq.write does not work

### ISSUE THREAD

**Issue by SWeinmueller** [pulseq-frame/pulseq-zero#9]
with pulseqzero.mr0_mode():
  seq, enc_phase, enc_part, adc_usage = TSE(**kwargs)
  seq0 = seq.to_mr0()

Is it possible to call then with seq.write the write function from pulseq?

**Comment by J-Endres** [comment]
No, pulseqzero does not contain the pulse shape / .seq writing code etc to support this.

You need to build the sequence in non-mr0 mode, then the installed pypulseq is used and the .seq can be written.

Writing from pulseq-zero is currently not on the roadmap, if there are valid reasons to support it please reopen and explain the use case.
